let token=localStorage.getItem("adminToken"), editing=null;
const $=id=>document.getElementById(id);
async function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:"Bearer "+token}:{})};const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||"Request failed");return d}
function showApp(){if(token){$("login").classList.add("hidden");$("app").classList.remove("hidden");loadOrders();}}
async function login(){try{const d=await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("password").value})});token=d.token;localStorage.setItem("adminToken",token);$("loginMsg").textContent="";showApp()}catch(e){$("loginMsg").textContent=e.message}}
function logout(){localStorage.removeItem("adminToken");token=null;location.reload()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$(b.dataset.page).classList.remove("hidden");if(b.dataset.page==="orders")loadOrders();if(b.dataset.page==="products")loadProducts();if(b.dataset.page==="settings")loadSettings()});
async function loadOrders(){try{const d=await api("/api/admin/orders");$("ordersList").innerHTML=d.orders.length?d.orders.map(o=>`<article class="order"><div class="order-head"><div><b>${esc(o.id)}</b><div class="muted">${new Date(o.createdAt).toLocaleString()}</div></div><span class="status">${esc(o.status)}</span></div><div class="order-grid"><div><b>Account</b><br>${esc(o.account)}</div><div><b>UID</b><br>${esc(o.uid)}</div><div><b>Item</b><br>${esc(o.product)}</div><div><b>Amount</b><br>₹${Number(o.amount).toFixed(2)}</div><div><b>Region</b><br>${esc(o.region||"—")}</div></div><div class="actions"><button class="good" onclick="setStatus('${o.id}','paid')">Paid</button><button onclick="setStatus('${o.id}','processing')">Processing</button><button class="good" onclick="setStatus('${o.id}','completed')">Completed</button><button class="bad" onclick="setStatus('${o.id}','rejected')">Reject</button></div></article>`).join(""):"<div class='panel'>No orders yet.</div>"}catch(e){if(e.message.includes("authentication"))logout();else alert(e.message)}}
async function setStatus(id,status){try{await api("/api/admin/orders/"+encodeURIComponent(id),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});loadOrders()}catch(e){alert(e.message)}}
async function loadProducts(){const d=await api("/api/admin/products");$("productsList").innerHTML=d.products.map(p=>`<article class="product-row"><div><h3>${esc(p.name)}</h3><span>${esc(p.mode)} • ₹${Number(p.price).toFixed(0)} • Stock ${Number(p.stock)} • ${p.active?"Visible":"Hidden"}</span></div><div class="product-actions"><button class="edit" onclick='editProduct(${JSON.stringify(p)})'>Edit</button></div></article>`).join("")}
function newProduct(){editProduct({id:"",name:"New Product",mode:"diamonds",price:0,mrp:0,bonus:"",stock:0,badge:"",image_url:"",active:true})}
function editProduct(p){editing=p;$("editTitle").textContent=p.id?"Edit product":"Add product";$("pId").value=p.id||"";$("pName").value=p.name||"";$("pMode").value=p.mode||"diamonds";$("pPrice").value=p.price||0;$("pMrp").value=p.mrp||0;$("pBonus").value=p.bonus||"";$("pStock").value=p.stock||0;$("pBadge").value=p.badge||"";$("pImage").value=p.image_url||"";$("pActive").checked=p.active!==false;$("deleteBtn").style.display=p.id?"inline-block":"none";$("editor").classList.remove("hidden")}
function closeEditor(){$("editor").classList.add("hidden")}
async function saveProduct(){const p={id:$("pId").value,name:$("pName").value,mode:$("pMode").value,price:Number($("pPrice").value),mrp:Number($("pMrp").value),bonus:$("pBonus").value,stock:Number($("pStock").value),badge:$("pBadge").value,image_url:$("pImage").value,active:$("pActive").checked};try{if(p.id)await api("/api/admin/products/"+encodeURIComponent(p.id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});else await api("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});closeEditor();loadProducts()}catch(e){alert(e.message)}}
async function deleteProduct(){if(!confirm("Delete this product?"))return;try{await api("/api/admin/products/"+encodeURIComponent($("pId").value),{method:"DELETE"});closeEditor();loadProducts()}catch(e){alert(e.message)}}
async function loadSettings(){const d=await api("/api/admin/settings");const s=d.settings||{};$("sName").value=s.storeName||"";$("sSub").value=s.subtitle||"";$("sUpi").value=s.upiId||"";$("sQr").value=s.qrUrl||"";$("sSupport").value=s.supportText||""}
async function saveSettings(){try{await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({storeName:$("sName").value,subtitle:$("sSub").value,upiId:$("sUpi").value,qrUrl:$("sQr").value,supportText:$("sSupport").value})});$("saveMsg").textContent="Saved successfully."}catch(e){$("saveMsg").textContent=e.message}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
showApp();
